### ISSUE TITLE
How to avoid `Cannot read property 'id' of undefined`

### ISSUE THREAD

**Issue by vincentdoerig** [JaneJeon/objection-authorize#153]
Hey, thanks for the great plugin. I was wondering how to avoid an error like `Cannot read property 'id' of undefined` when creating a call like this:
```js
const posts = Post.query()
  .authorize(req.user)
  .where('user_id', req.user.id)
```
If a user is not logged in, there is no user id, hence the error. Is there a way to throw the auth error before evaluating the where statement, or how would you handle this?

**Comment by JaneJeon** [comment]
Well, the error is clear: it’s on the 3rd line `req.user.id`, *not* in the plugin itself.

The plugin only handles req.user potentially being empty inside the ACLs - it can’t affect anything outside the scope of that for obvious reasons.
