### ISSUE TITLE
What is the library parameter during initialization?

### ISSUE THREAD

**Issue by BadPistol97** [JaneJeon/objection-authorize#158]
>const acl = ... // see below for defining acl
> const { Model } = require('objection')
> const authorize = require('objection-authorize')(acl, library[, opts])
> 
> class Post extends authorize(Model) {
>   // That's it! This is just a regular objection.js model class
> }

does the library parameter mean instance of CASL?

**Comment by JaneJeon** [comment]
Library is the name of the authorization library, in string (in this case it would be `casl`). The `acl` property is the actual instance of CASL.
